
# Title: Binary Search Trees
# Author: Arman Engin Sucu
# ID: 21801777
# Section: 1
# Assignment: 2
# Description: Makefile for Hw2

output: main.o BinaryNode.o BinarySearchTree.o
	g++ main.o BinaryNode.o BinarySearchTree.o -o output

main.o: main.cpp
	g++ -c main.cpp

BinaryNode.o: BinaryNode.cpp BinaryNode.h
	g++ -c BinaryNode.cpp 

BinarySearchTree.o: BinarySearchTree.cpp BinarySearchTree.h
	g++ -c BinarySearchTree.cpp