
# Title: Heap and Priority Queue
# Author: Arman Engin Sucu
# ID: 21801777
# Section: 1
# Assignment: 3
# Description: Makefile for Hw3

output: main.o simulator.o
	g++ main.o simulator.o -o output

main.o: main.cpp
	g++ -std=c++11 -c main.cpp

simulator.o: simulator.cpp simulator.h
	g++ -std=c++11 -c simulator.cpp 
