
# Title: Sorting and Algorithm Efficiency
# Author: Arman Engin Sucu
# ID: 21801777
# Section: 1
# Assignment: 1
# Description: a makefile to create an executable for Hw1


output: main.o sorting.o
	g++ main.o sorting.o -o output

main.o: main.cpp
	g++ -c main.cpp

sorting.o: sorting.cpp sorting.h
	g++ -c sorting.cpp